# Generated by Django 3.2.7 on 2021-09-18 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210916_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritemeal',
            name='created',
        ),
        migrations.AddField(
            model_name='favouritemeal',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
