# Generated by Django 3.2.7 on 2021-09-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_favouritemeal_meal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritemeal',
            unique_together={('meal', 'user')},
        ),
    ]
